/**
 * Generate statusline/emoji-widths.data from Unicode's Emoji_Presentation
 * property. The bash statusline renderer loads this file because awk has no
 * Unicode property escapes; server/art.ts uses the same regex directly.
 *
 * Regenerate:  bun run gen:emoji-widths
 *
 * The emitted list holds every codepoint with Emoji_Presentation=Yes, so the
 * bash width walker stays in parity with server/art.ts for both BMP symbols
 * and supplementary-plane emoji.

 */
import { writeFileSync } from "fs";
import { join } from "path";

const OUT = join(import.meta.dir, "..", "statusline", "emoji-widths.data");
const TEXT_OUT = join(import.meta.dir, "..", "statusline", "emoji-text.data");

const EMOJI_PRES_RE = /\p{Emoji_Presentation}/u;
const EMOJI_RE = /\p{Emoji}/u;
const presentation: number[] = [];
const textDefault: number[] = [];
for (let cp = 0; cp <= 0x10FFFF; cp++) {
  const character = String.fromCodePoint(cp);
  if (EMOJI_PRES_RE.test(character)) presentation.push(cp);
  else if (EMOJI_RE.test(character)) textDefault.push(cp);
}

function encodeRanges(codepoints: number[]): string {
  const ranges: string[] = [];
  let start = codepoints[0];
  let end = start;
  for (const codepoint of codepoints.slice(1)) {
    if (codepoint === end + 1) {
      end = codepoint;
      continue;
    }
    ranges.push(start === end ? String(start) : `${start}-${end}`);
    start = end = codepoint;
  }
  ranges.push(start === end ? String(start) : `${start}-${end}`);
  return ranges.join(",");
}

const header = "# Auto-generated by scripts/gen-emoji-widths.ts — do not edit by hand.";
writeFileSync(OUT, [
  header,
  "# Decimal codepoint ranges with Unicode Emoji_Presentation=Yes.",
  encodeRanges(presentation),
  "",
].join("\n"));
writeFileSync(TEXT_OUT, [
  header,
  "# Decimal codepoint ranges with Unicode Emoji=Yes and Emoji_Presentation=No.",
  encodeRanges(textDefault),
  "",
].join("\n"));
console.log(`Wrote ${presentation.length} presentation and ${textDefault.length} text-default codepoints`);
